Repository JuliaRobotics/ApproxManifoldProducts.jl, pull requests merged in 2021-09, with the labels that each got.

#156 expand dispatch on int for partial vector
  src/services/ManifoldPartials.jl
Labels: enhancement, API, standardization, partials

#160 Allow complex manifolds in ManifoldKernelDensity
  src/entities/ManifoldKernelDensity.jl
Labels: enhancement, bug fix, manifolds

#159 new test on issue with partial product of SE(2)
  Project.toml
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/Legacy.jl
  src/services/ManifoldKernelDensity.jl
  test/runtests.jl
  test/testManifoldPartial.jl
  test/testMarginalProducts.jl
  test/testPartialProductSE2.jl
  test/testdata/partialtest.jld2
Labels: bug, testing, downstream

#161 set partials product test
  Project.toml
  test/testPartialProductSE2.jl
Labels: enhancement, testing, partials

#162 v0.4.17-rc1
  Project.toml
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/Legacy.jl
  src/entities/ManifoldKernelDensity.jl
  src/services/ManifoldKernelDensity.jl
  src/services/ManifoldPartials.jl
  test/runtests.jl
  test/testManifoldPartial.jl
  test/testMarginalProducts.jl
  test/testPartialProductSE2.jl
  test/testdata/partialtest.jld2
Labels: release

#164 fix print mean for show MKD on ProductRepr
  src/services/ManifoldKernelDensity.jl
Labels: enhancement
