Repository JuliaRobotics/ApproxManifoldProducts.jl, pull requests merged in 2021-07, with the labels that each got.

#90 wip, vector{P} proper
  Project.toml
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/Deprecated.jl
  src/Interface.jl
  src/KernelHilbertEmbeddings.jl
  src/Legacy.jl
  src/ManifoldDefinitions.jl
  src/Serialization.jl
  src/entities/ManifoldDefinitions.jl
  src/entities/ManifoldKernelDensity.jl
  src/services/Circular.jl
  src/services/ManifoldKernelDensity.jl
  test/basic_se3.jl
  test/testBasicManiProduct.jl
  test/testManiProductBigSmall.jl
Labels: API, deprecation, enhancement, standardization, work in progress

#91 depr fixes
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/CommonUtils.jl
  src/Deprecated.jl
  src/Interface.jl
  src/entities/ManifoldDefinitions.jl
  src/services/CircularUtils.jl
  src/services/Euclidean.jl
  src/services/ManifoldKernelDensity.jl
Labels: API, bug fix, deprecation

#92 release v0.4.1-rc1
  Project.toml
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/CommonUtils.jl
  src/Deprecated.jl
  src/Interface.jl
  src/KernelHilbertEmbeddings.jl
  src/Legacy.jl
  src/ManifoldDefinitions.jl
  src/Serialization.jl
  src/entities/ManifoldDefinitions.jl
  src/entities/ManifoldKernelDensity.jl
  src/services/Circular.jl
  src/services/CircularUtils.jl
  src/services/Euclidean.jl
  src/services/ManifoldKernelDensity.jl
  test/basic_se3.jl
  test/testBasicManiProduct.jl
  test/testManiProductBigSmall.jl
Labels: release, versioning

#94 Bugfix manifoldProduct oldpoints to coordinates
  src/API.jl
  src/entities/ManifoldKernelDensity.jl
  test/testMarginalProducts.jl
Labels: bug fix, downstream

#95 calcMean always returns a point
  src/services/ManifoldKernelDensity.jl
Labels: bug fix, downstream, manifolds

#96 tag v0.4.2-rc1
  Project.toml
  src/API.jl
  src/entities/ManifoldKernelDensity.jl
  src/services/ManifoldKernelDensity.jl
  test/testMarginalProducts.jl
Labels: release

#99 add getManifoldPartial
  Project.toml
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/Interface.jl
  src/services/ManifoldKernelDensity.jl
  src/services/ManifoldPartials.jl
  test/runtests.jl
  test/testManifoldPartial.jl
Labels: API, enhancement, manifolds, partials

#101 fix manifoldProduct
  src/API.jl
Labels: bug fix, partials

#100 v0.4.3-rc1
  Project.toml
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/Interface.jl
  src/services/ManifoldKernelDensity.jl
  src/services/ManifoldPartials.jl
  test/runtests.jl
  test/testManifoldPartial.jl
Labels: release

#103 API updates for partial and getPoints
  Project.toml
  src/API.jl
  src/services/ManifoldKernelDensity.jl
  src/services/ManifoldPartials.jl
  test/testManifoldPartial.jl
Labels: enhancement, partials, testing

#105 try show mean mkd
  src/services/ManifoldKernelDensity.jl
Labels: enhancement, user experience

#104 v0.4.4-rc1
  Project.toml
  src/API.jl
  src/services/ManifoldKernelDensity.jl
  src/services/ManifoldPartials.jl
  test/testManifoldPartial.jl
Labels: release

#107 add MKD.infoPerCoord
  Project.toml
  src/API.jl
  src/Interface.jl
  src/entities/ManifoldKernelDensity.jl
  src/services/ManifoldKernelDensity.jl
Labels: enhancement, types

#108 v0.4.5-rc1
  Project.toml
  src/API.jl
  src/Interface.jl
  src/entities/ManifoldKernelDensity.jl
  src/services/ManifoldKernelDensity.jl
Labels: release

#110 add calcVariableCovarianceBasic, upstream from IIF
  Project.toml
  src/ApproxManifoldProducts.jl
  src/CommonUtils.jl
Labels: API, downstream, enhancement, standardization

#111 v0.4.6-rc1
  Project.toml
  src/ApproxManifoldProducts.jl
  src/CommonUtils.jl
Labels: release

#113 fixes found downstream w TranslationGroup
  Project.toml
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/Legacy.jl
Labels: bug fix, downstream

#114 v0.4.7-rc1
  Project.toml
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/Legacy.jl
Labels: release

#116 mv Serialization.jl downstream to IIF
  Project.toml
  src/ApproxManifoldProducts.jl
  src/Interface.jl
  src/Serialization.jl
Labels: decision, downstream, refactor

#117 v0.4.8-rc1
  Project.toml
  src/ApproxManifoldProducts.jl
  src/Interface.jl
  src/Serialization.jl
Labels: release

#121 v0.4.9-rc1
  Project.toml
  src/Legacy.jl
  src/services/ManifoldKernelDensity.jl
Labels: release

#123 add calcProductGaussians, mean, isPartial
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/CommonUtils.jl
  src/services/ManifoldKernelDensity.jl
Labels: API, dependencies, enhancement

#124 broadcast assign MMatrix
  src/CommonUtils.jl
Labels: enhancement, maintenance

#119 Better testing for product of only marginals
  NEWS.md
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/CommonUtils.jl
  src/Deprecated.jl
  src/services/ManifoldKernelDensity.jl
  test/testMarginalProducts.jl
Labels: enhancement, partials, testing, work in progress

#125 fix tests
  src/services/ManifoldKernelDensity.jl
  test/testMarginalProducts.jl
Labels: bug fix, enhancement, maintenance, testing

#126 v0.4.10-rc1
  NEWS.md
  Project.toml
  src/API.jl
  src/ApproxManifoldProducts.jl
  src/CommonUtils.jl
  src/Deprecated.jl
  src/services/ManifoldKernelDensity.jl
  test/testMarginalProducts.jl
Labels: release

#128 add better docs getManifoldPartial
  src/services/ManifoldPartials.jl
Labels: documentation, enhancement
