Repository JuliaRobotics/ApproxManifoldProducts.jl, pull requests merged in 2021-08, with the labels that each got.

#129 fix constructor marginal of marginal
  src/services/ManifoldKernelDensity.jl
  test/testManifoldPartial.jl
Labels: bug fix, partials

#130 v0.4.11-rc1
  Project.toml
  src/services/ManifoldKernelDensity.jl
  src/services/ManifoldPartials.jl
  test/testManifoldPartial.jl
Labels: release

#133 new replace function
  Project.toml
  src/API.jl
  src/Deprecated.jl
  src/Interface.jl
  src/services/ManifoldKernelDensity.jl
  test/testManifoldPartial.jl
Labels: API, deprecation, enhancement, partials, testing

#135 product can now return partials, and testing
  src/API.jl
  src/services/ManifoldKernelDensity.jl
  test/testMarginalProducts.jl
Labels: enhancement, partials

#134 v0.4.12-rc1
  Project.toml
  src/API.jl
  src/Deprecated.jl
  src/Interface.jl
  src/services/ManifoldKernelDensity.jl
  test/testManifoldPartial.jl
  test/testMarginalProducts.jl
Labels: release

#137 MKD helpers now ignore partial if full
  src/API.jl
  src/services/ManifoldKernelDensity.jl
Labels: enhancement, partials, standardization

#139 Fix identity to identity_element for Manifolds 0.6
  Project.toml
  src/API.jl
  src/Interface.jl
  src/services/ManifoldKernelDensity.jl
  src/services/ManifoldPartials.jl
  test/basic_se3.jl
  test/testBasicManiProduct.jl
  test/testManiProductBigSmall.jl
Labels: API, compat, upstream, bug fix, manifolds

#140 fix import, and setPointMani! and Partial
  src/Interface.jl
Labels: enhancement, API, downstream, bug fix, manifolds

#141 bug fix
  src/Interface.jl
Labels: bug fix, manifolds

#138 v0.4.13-rc1
  Project.toml
  src/API.jl
  src/Interface.jl
  src/services/ManifoldKernelDensity.jl
  src/services/ManifoldPartials.jl
  test/basic_se3.jl
  test/testBasicManiProduct.jl
  test/testManiProductBigSmall.jl
Labels: release

#143 more marginal features
  src/Interface.jl
  src/services/ManifoldKernelDensity.jl
Labels: enhancement

#144 v0.4.14-rc1
  Project.toml
  src/Interface.jl
  src/services/ManifoldKernelDensity.jl
Labels: release

#146 getInfoPerCoord, getBandwidth and fix
  Project.toml
  src/services/ManifoldKernelDensity.jl
Labels: enhancement, bug fix

#147 v0.4.15-rc1
  Project.toml
  src/services/ManifoldKernelDensity.jl
Labels: release

#149 std to TranslationGroup
  src/Legacy.jl
  src/entities/ManifoldDefinitions.jl
  src/services/ManifoldPartials.jl
  test/testBasicManiProduct.jl
  test/testManifoldPartial.jl
Labels: testing, maintenance, standardization, manifolds

#153 api instead setPointPartial!
  src/Deprecated.jl
  src/Interface.jl
  src/services/ManifoldKernelDensity.jl
Labels: API, standardization, deprecation

#154 v0.4.16-rc1
  Project.toml
  src/Deprecated.jl
  src/Interface.jl
  src/Legacy.jl
  src/entities/ManifoldDefinitions.jl
  src/services/ManifoldKernelDensity.jl
  src/services/ManifoldPartials.jl
  test/testBasicManiProduct.jl
  test/testManifoldPartial.jl
Labels: release
