Repository JuliaRobotics/ApproxManifoldProducts.jl, pull requests merged in 2022-07, with the labels that each got.

#205 Upgrade to support ArrayPartition
  Project.toml
  src/ApproxManifoldProducts.jl
  src/Interface.jl
  src/services/ManifoldPartials.jl
  test/basic_se3.jl
  test/testBasicManiProduct.jl
  test/testManiProductBigSmall.jl
  test/testManifoldConventions.jl
  test/testManifoldPartial.jl
  test/testPartialProductSE2.jl
  test/testSymmetry.jl
Labels: enhancement, work in progress, breaking changes, manifolds

#206 depr _makeVectorManifold
  src/Deprecated.jl
  src/Interface.jl
Labels: standardization, deprecation

#208 rm depr for v0.5
  src/Deprecated.jl
  test/testMMD.jl
Labels: API, maintenance, breaking changes, deprecation

#209 more deprecations
  src/Deprecated.jl
  src/entities/ManifoldDefinitions.jl
Labels: maintenance, deprecation

#212 minor improvements
  src/ApproxManifoldProducts.jl
  src/services/ManifoldKernelDensity.jl
Labels: API, maintenance, standardization

#214 some cleanup on rotations, and compat Rotations
  Project.toml
  src/ApproxManifoldProducts.jl
  src/Deprecated.jl
Labels: maintenance, standardization
