Repository JuliaRobotics/ApproxManifoldProducts.jl, pull requests merged in 2022-12, with the labels that each got.

#219 add JL 1.9 to CI
  .github/workflows/ci.yml
Labels: CI, julia version

#220 consolidation towards Manifolds.jl cov
  src/CommonUtils.jl
  src/Deprecated.jl
  src/ExportAPI.jl
Labels: enhancement, maintenance, deprecation

#221 Fix and test mkd stats
  src/CommonUtils.jl
  test/runtests.jl
  test/testMKDStats.jl
Labels: testing, bug fix

#222 fix stats fun duplication
  src/CommonUtils.jl
  src/services/ManifoldKernelDensity.jl
  test/testMKDStats.jl
Labels: maintenance, refactor, bug fix

#223 fix mean of mkd function
  Project.toml
  src/CommonUtils.jl
Labels: bug fix, partials

#224 release v0.6.2-rc1
  .github/workflows/ci.yml
  Project.toml
  src/CommonUtils.jl
  src/Deprecated.jl
  src/ExportAPI.jl
  src/services/ManifoldKernelDensity.jl
  test/runtests.jl
  test/testMKDStats.jl
Labels: release
