Repository JuliaRobotics/ApproxManifoldProducts.jl, pull requests merged in 2023-10, with the labels that each got.

#249 mini cleanup
  src/API.jl
  src/services/ManifoldKernelDensity.jl
Labels: enhancement

#250 some docs and cleanup
  src/entities/ManifoldKernelDensity.jl
  src/services/ManifoldKernelDensity.jl
Labels: enhancement, standardization, documentation

#251 v0.8.1-rc1
  Project.toml
  src/API.jl
  src/entities/ManifoldKernelDensity.jl
  src/services/ManifoldKernelDensity.jl
Labels: release

#253 setPointsMani! of array from point
  src/Interface.jl
Labels: enhancement

#254 v0.8.2-rc1
  Project.toml
  src/Interface.jl
Labels: release

#259 v0.8.3-rc1
  Project.toml
  src/ApproxManifoldProducts.jl
  src/Deprecated.jl
  src/ExportAPI.jl
  src/Interface.jl
  src/KernelHilbertEmbeddings.jl
  src/services/KernelEval.jl
  src/services/ManellicTree.jl
  src/services/ManifoldPartials.jl
  test/basic_se3.jl
  test/testManiProductBigSmall.jl
Labels: release

#261 Less allocs in resid2DLinear and faster mean
  src/CommonUtils.jl
Labels: performance
