Repository JuliaRobotics/ApproxManifoldProducts.jl, pull requests merged in 2024-05, with the labels that each got.

#290 More testing on tree eval and products
  src/services/KernelEval.jl
  test/manellic/testManellicTree.jl
Labels: testing, bug fix

#291 manellic construction uses updateBW instead
  src/entities/KernelEval.jl
  src/services/KernelEval.jl
  src/services/ManellicTree.jl
  src/services/ManifoldKernelDensity.jl
  test/manellic/testManellicTree.jl
Labels: enhancement, testing, performance

#292 multidim optim of manellic and test
  src/services/ManifoldKernelDensity.jl
  test/manellic/testManellicTree.jl
Labels: enhancement, testing

#293 multidim manellic on SE2
  src/services/ManellicTree.jl
  src/services/ManifoldKernelDensity.jl
  test/manellic/testManellicTree.jl
  test/testMarginalProducts.jl
Labels: enhancement, testing

#294 test manellic construct SE3
  test/manellic/testManellicTree.jl
Labels: testing
